punny_jokes = [
    "I don't trust stairs. They're always up to something.",
    "Did you hear about the cheese factory that exploded? There was nothing left but de-brie.",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "I used to play piano by ear, but now I use my hands.",
    "Why don't scientists trust atoms? Because they make up everything.",
    "I would tell you a joke about an elevator, but it's an uplifting experience.",
    "I used to be a baker, but I couldn't make enough dough.",
    "Have you heard about that restaurant on the moon? Great food, no atmosphere.",
    "I'm on a seafood diet. I see food and I eat it.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "What's orange and sounds like a parrot? A carrot.",
    "Parallel lines have so much in common. It's a shame they'll never meet.",
    "Why do cows wear bells? Because their horns don't work.",
    "What do you call a fake noodle? An impasta.",
    "I hate Russian dolls… they're so full of themselves.",
    "Did you hear about the mathematician who’s afraid of negative numbers? He'll stop at nothing to avoid them.",
    "Don't trust people who do acupuncture. They're back stabbers.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "I used to be a shoe salesman, but I didn’t fit in.",
    "What’s brown and sticky? A stick.",
    "What do you call a can opener that doesn’t work? A can’t opener.",
    "Did you hear about the man who stole a calendar? He got 12 months.",
    "I wondered why the baseball was getting bigger. Then it hit me.",
    "Why did the bike fall over? It was two-tired.",
    "Why don’t skeletons fight each other? They don’t have the guts.",
    "I wanted to make a belt out of watches, but it was a waist of time.",
    "What did one hat say to the other? Stay here, I'm going on ahead.",
    "Did you hear about the magic tractor? It turned into a field.",
    "Why are ghosts bad at lying? Because you can see right through them.",
    "What time did the man go to the dentist? Tooth-hurty.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "How do you organize a space party? You planet.",
    "Did you hear about the guy who invented Lifesavers? He made a mint!",
    "Why don't eggs tell jokes? They might crack up.",
    "What do you call a factory that makes good products? A satisfactory.",
    "When does a joke become a \"dad\" joke? When it becomes apparent.",
    "What did the buffalo say to his son when he dropped him off at school? Bison.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why can’t you give Elsa a balloon? Because she will let it go.",
    "Want to hear a joke about construction? I’m still working on it.",
    "How do you make a tissue dance? Put a little boogey in it.",
    "Why don't seagulls fly over the bay? Because then they'd be bagels.",
    "What do you call a snowman with a six-pack? An abdominal snowman.",
    "How does a penguin build its house? Igloos it together.",
    "Why are frogs so happy? Because they eat whatever bugs them.",
    "Why did the math book look sad? Because it had too many problems.",
    "What’s Forrest Gump’s password? 1forest1.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "Why did the computer go to the doctor? Because it had a virus!"
]
